// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "poc/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// FindAllUsers is an autogenerated mock type for the FindAllUsers type
type FindAllUsers struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *FindAllUsers) Execute() ([]domain.User, error) {
	ret := _m.Called()

	var r0 []domain.User
	if rf, ok := ret.Get(0).(func() []domain.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
