// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "poc/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// FindUserById is an autogenerated mock type for the FindUserById type
type FindUserById struct {
	mock.Mock
}

// Execute provides a mock function with given fields: id
func (_m *FindUserById) Execute(id uuid.UUID) (domain.User, error) {
	ret := _m.Called(id)

	var r0 domain.User
	if rf, ok := ret.Get(0).(func(uuid.UUID) domain.User); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
