// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "poc/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// SaveUser is an autogenerated mock type for the SaveUser type
type SaveUser struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *SaveUser) Execute(_a0 domain.User) (domain.User, error) {
	ret := _m.Called(_a0)

	var r0 domain.User
	if rf, ok := ret.Get(0).(func(domain.User) domain.User); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.User) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
