// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "poc/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// UpdateUser is an autogenerated mock type for the UpdateUser type
type UpdateUser struct {
	mock.Mock
}

// Execute provides a mock function with given fields: id, _a1
func (_m *UpdateUser) Execute(id uuid.UUID, _a1 domain.User) (domain.User, error) {
	ret := _m.Called(id, _a1)

	var r0 domain.User
	if rf, ok := ret.Get(0).(func(uuid.UUID, domain.User) domain.User); ok {
		r0 = rf(id, _a1)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID, domain.User) error); ok {
		r1 = rf(id, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
