CREATE TABLE IF NOT EXISTS USERS (
    ID VARCHAR(36) PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT clock_timestamp() NOT NULL,
    DELETED_AT TIMESTAMP
);